[package]
name = "day24"
version = "0.1.0"
edition = "2021"
default-run = "day24"

[[bin]]
name = "day24"
path = "src/main.rs"

[[bin]]
name = "columnize"
path = "src/columnize.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
